### ISSUE TITLE
cannot get it working on xubuntu 15.04

### ISSUE THREAD

**Issue by kinocz** [dorkbox/SystemTray#1]
I'm not sure what I'm doing wrong, since I do not understand jni. Library in system is existing, but cannot be loaded (I think). I'm running amd64 machine with amd64 java patched with font infinality(nicer fornts).

```
/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -Didea.launcher.port=7533 -Didea.launcher.bin.path=/home/kino/programs/idea/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/management-agent.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/jfxswt.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/icedtea-sound.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/java-atk-wrapper.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/lib/ext/localedata.jar:/home/kino/Documents/projects/redmineClient/out/production/redmineClient:/home/kino/Documents/projects/redmineClient/lib/SystemTray_v1.0.jar:/home/kino/Documents/projects/redmineClient/lib/slf4j-api-1.7.5.jar:/home/kino/Documents/projects/redmineClient/lib/dorkboxUtil_v1.0.jar:/home/kino/Documents/projects/redmineClient/lib/jna/jna-4.1.0.jar:/home/kino/Documents/projects/redmineClient/lib/jna/jna-platform-4.1.0.jar:/home/kino/programs/idea/lib/idea_rt.jar com.intellij.rt.execution.application.AppMain cz.kinovic.redmineClient.Main
Fontconfig warning: "/etc/fonts/infinality/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/infinality/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.sun.jna.Native.sizeof(I)I
	at com.sun.jna.Native.sizeof(Native Method)
	at com.sun.jna.Native.<clinit>(Native.java:132)
	at dorkbox.util.jna.linux.Gtk.<clinit>(Gtk.java:12)
	at dorkbox.util.jna.linux.GtkSupport.<clinit>(GtkSupport.java:11)
	at dorkbox.util.tray.SystemTray.<clinit>(SystemTray.java:76)
	at cz.kinovic.redmineClient.Main.main(Main.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

```
locate libgtk-x11-2.0.so
/usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0
/usr/lib/i386-linux-gnu/libgtk-x11-2.0.so.0.2400.27
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0.2400.27
```

**Comment by dorkbox** [comment]
I tested it on Ubuntu 14.04 -- I'll startup a xubuntu 15.04x64 VM and see what's going on.

**Comment by dorkbox** [comment]
@kinocz Did you use my JNA jars or the official ones? Mine do not automatically load the native parts necessary to operate (since the system I use this in loads them for me).

**Comment by kinocz** [comment]
I did take your project as whole with included jna, but good point trying out the system ones. I will take a look into it over weekend and post more results.

**Comment by dorkbox** [comment]
I noticed that there are problems with appindicators on xubuntu -- not sure how to proceed,  as it appears xubuntu should support them. I'll see what else I can dig up, it might be that appindicators are not necessary in xubuntu (so I'll have to change some logic to check for that)

**Comment by kinocz** [comment]
got it working as appindicator.
Had to download jna from: https://github.com/twall/jna
install appindicator with proper version libappindicator1 (I had only libappindicator3-1 installed)

note: using system libjna-java did not help.

**Comment by dorkbox** [comment]
I'm glad it's working. Thanks for your feedback on this.

I'll see if I can get it working with libappindicator3-1 (or with whatever is a fallback) as well --- I'll also include instructions for loading the native libraries as part of my example.

**Comment by dorkbox** [comment]
@kinocz - i added some safeguards to the loading process, so if the SystemTray finds libappindicator, but fails to load it, the SystemTray will fall-back to GTK instead.

It passed tests in a VM (xbununtu 15.04x64, stock install) -- so you should be good-to-go if you need to run this on other linux systems were a wonky version of libappindicator is used.
