### ISSUE TITLE
Error : Graphics Device initialization failed for :  es2, sw

### ISSUE THREAD

**Issue by pravya191** [dorkbox/SystemTray#101]
hi ,
    I am using dork box to set tray icon . in ubuntu its working properly . When i am trying to do the same in MAC systems . I got the error as follows . May I know the reason ??
Jdk used is  jdk1.8.0_201.jdk
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
    at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
    at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:221)
    at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:248)
    at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
    at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$412(LauncherImpl.java:182)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
    ... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
    at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:260)
    at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
    at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:675)
    at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:695)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$412(LauncherImpl.java:182)
    at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by dorkbox** [comment]
is this on a VM or on MAC hardware? (of note, JavaFX will only work on MAC hardware)

**Comment by pravya191** [comment]
This issue is occured in  MAC systems

**Comment by dorkbox** [comment]
OK, I'll check out the JavaFX build on my MAC.

**Comment by pravya191** [comment]
thank u for response

**Comment by timo-reymann** [comment]
Same problem here.

**Comment by dorkbox** [comment]
JavaFX on MacOS is now working.

Thanks for the bug report!
