### ISSUE TITLE
JNA dependency update

### ISSUE THREAD

**Issue by pietrygamat** [dorkbox/SystemTray#103]
The project depends on [JNA ](https://github.com/java-native-access/jna)v4.x while the v5.x is out. It's problematic when trying to use some other libraries that depend on updated version ([oshi/oshi](https://github.com/oshi/oshi)), because there are api changes between the two. Is there a plan to upgrade to the latest jna?

```
Exception in thread "WindowsEventDispatch" java.lang.IllegalArgumentException: Invalid Structure field in class dorkbox.util.jna.windows.MSG, field name 'wParam' (class dorkbox.util.jna.windows.Parameter): The type "dorkbox.util.jna.windows.Parameter" is not supported: Can't create an instance of class dorkbox.util.jna.windows.Parameter, requires a public no-arg constructor: java.lang.reflect.InvocationTargetException
	at com.sun.jna.Structure.validateField(Structure.java:1214)
	at com.sun.jna.Structure.validateFields(Structure.java:1223)
	at com.sun.jna.Structure.<init>(Structure.java:200)
	at com.sun.jna.Structure.<init>(Structure.java:193)
	at com.sun.jna.Structure.<init>(Structure.java:180)
	at com.sun.jna.Structure.<init>(Structure.java:172)
	at dorkbox.util.jna.windows.MSG.<init>(MSG.java:25)
	at dorkbox.util.jna.windows.WindowsEventDispatch.run(WindowsEventDispatch.java:195)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: The type "dorkbox.util.jna.windows.Parameter" is not supported: Can't create an instance of class dorkbox.util.jna.windows.Parameter, requires a public no-arg constructor: java.lang.reflect.InvocationTargetException
	at com.sun.jna.Native.getNativeSize(Native.java:1356)
	at com.sun.jna.Structure.getNativeSize(Structure.java:2172)
	at com.sun.jna.Structure.getNativeSize(Structure.java:2162)
	at com.sun.jna.Structure.validateField(Structure.java:1210)
	... 8 more
```

**Comment by dorkbox** [comment]
yea, i'll update it. not sure exactly when - since there is a lot of other going on.

**Comment by polyn0m** [comment]
@dorkbox you plan update? It's painful issue...

**Comment by camhart** [comment]
> @dorkbox you plan update? It's painful issue...

It's an open source project, he's built and giving away for free.  Why don't you put up a PR to fix the problem and help him out?

**Comment by bdw429s** [comment]
Just subscribing here.  I'm using Systemtray along side https://github.com/jline/jline3 which now requires JNA 5.3 or higher.

**Comment by dyorgio** [comment]
Subscribing too...
It's hard do help with PR, because this lib depends of Util lib, that is used for a lot of @dorkbox.
My sugestion (2 cents): migrate all dependency utilities/classes sources to SystemTray project, making it a standalone library (no others dorkbox suite deps).

**Comment by dorkbox** [comment]
Because of java 11+ changes to JNA, i will be changing how class re-writing happens. This will be transparent to the end user, and should provide better support with fewer issues.

**Comment by dorkbox** [comment]
This is now compatible with the latest version of JNA.
