### ISSUE TITLE
NullPointerException when changing display scaling settings

### ISSUE THREAD

**Issue by cmf-cv** [dorkbox/SystemTray#107]
When changing the display scaling settings on Windows 10 from e.g. 200% to 350% on a 4K display there is a NullPointerException. This seems to happen each time I change the scaling setting. This is my debug output:

```
[JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - OS: Windows 10
[JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Arch: amd64
[JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Oracle Corporation OpenJDK 64-Bit Server VM 12
[JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Is Auto sizing tray/menu? true
[JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Is JavaFX detected? true
[JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Is SWT detected? false
[JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Java Swing L&F: Metal
[JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Auto-detecting tray type
[JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Tray indicator image size: 32
[JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Tray menu image size: 30
[JavaFX Application Thread] INFO dorkbox.systemTray.SystemTray - Successfully loaded type: _WindowsNativeTray
[WindowsEventDispatch] ERROR dorkbox.util.jna.windows.WindowsEventDispatch - Error during listener execution.
java.lang.NullPointerException
	at dorkbox.util.jna.windows.structs.NOTIFYICONDATA.setTooltip(NOTIFYICONDATA.java:70)
	at dorkbox.systemTray.ui.swing._WindowsNativeTray.show(_WindowsNativeTray.java:265)
	at dorkbox.systemTray.ui.swing._WindowsNativeTray.access$800(_WindowsNativeTray.java:57)
	at dorkbox.systemTray.ui.swing._WindowsNativeTray$2.run(_WindowsNativeTray.java:172)
	at dorkbox.util.jna.windows.WindowsEventDispatch$1.callback(WindowsEventDispatch.java:171)
	at dorkbox.util.jna.windows.User32_64.GetMessage(Native Method)
	at dorkbox.util.jna.windows.WindowsEventDispatch.run(WindowsEventDispatch.java:196)
	at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by dorkbox** [comment]
Fixed. Totally didn't think about what would happen during display scaling changes. Of note, the "swing" tray type cannot detect scaling changes, because swing doesn't react in a way I know about when this happens.  The "WindowsNativeTray" uses JNA to create a tray the same way a C++ application would, and I'm able to redraw the tray the correct way when the scale changes.

Thanks for the report!
