### ISSUE TITLE
ERROR: Unable to create tray type: '_WindowsNativeTray'

### ISSUE THREAD

**Issue by s-glatshtein** [dorkbox/SystemTray#112]
Hi,
We deploy OpenJDK 13 with our application and use it to run the jar that uses Dorkbox to create a system tray icon. I'm getting this error in some windows machines when trying to create a system tray for my application (but not all):

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by dorkbox.util.JavaFX (file:/<MyFolder>/lib/SystemTray-3.14.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of dorkbox.util.JavaFX
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2019-11-25 11:54:54.020 ERROR d.s.SystemTray
                                Unable to create tray type: '_WindowsNativeTray'
java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
        at dorkbox.systemTray.SystemTray.init(SystemTray.java:991)
        at dorkbox.systemTray.SystemTray.get(SystemTray.java:1073)
        at myprogram.b.b(MyProgram:1260)
        at myprogram.Program.main(MyProgram:40)
Caused by: java.lang.UnsatisfiedLinkError: C:\<MyFolder>\jre\bin\javaaccessbridge.dll: Can't find dependent libraries
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2440)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2497)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2648)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:806)
        at java.base/java.lang.System.loadLibrary(System.java:1906)
        at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$3.run(AccessBridge.java:116)
        at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge$3.run(AccessBridge.java:114)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:449)
        at jdk.accessibility/com.sun.java.accessibility.internal.AccessBridge.<clinit>(AccessBridge.java:113)
        at jdk.accessibility/com.sun.java.accessibility.internal.ProviderImpl.activate(ProviderImpl.java:58)
        at java.desktop/java.awt.Toolkit.lambda$loadAssistiveTechnologies$0(Toolkit.java:526)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
        at java.desktop/java.awt.Toolkit.loadAssistiveTechnologies(Toolkit.java:521)
        at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:598)
        at java.desktop/javax.swing.UIManager.<clinit>(UIManager.java:383)
        at java.desktop/javax.swing.JPopupMenu.updateUI(JPopupMenu.java:220)
        at java.desktop/javax.swing.JPopupMenu.<init>(JPopupMenu.java:188)
        at java.desktop/javax.swing.JPopupMenu.<init>(JPopupMenu.java:173)
        at dorkbox.systemTray.ui.swing.TrayPopup.<init>(TrayPopup.java:57)
        at dorkbox.systemTray.ui.swing.SwingMenu.<init>(SwingMenu.java:50)
        at dorkbox.systemTray.ui.swing._WindowsNativeTray$1.<init>(_WindowsNativeTray.java:73)
        at dorkbox.systemTray.ui.swing._WindowsNativeTray.<init>(_WindowsNativeTray.java:73)
        ... 9 common frames omitted
```

Please let me know at your earliest convenience if you require any more information or know the cause of this.

**Comment by s-glatshtein** [comment]
Any update on this issue? We haven't been able to find any more information

**Comment by dorkbox** [comment]
Hey, sorry for taking so long -- i've been extremely busy with work.

Why this is happening --- I'm not sure. There are some remaining issues that I need to sort out regarding JNA before I can work on this.

**Comment by s-glatshtein** [comment]
Hello,
Any news on the issue? Been quite some time

**Comment by dorkbox** [comment]
So I'm not sure why this is happening on some machines but not others. On the machines that it is *not* working on, have you examined the paths? From searching online, this problem seems to appear when the java installation doesn't setup paths correctly.

**Comment by s-glatshtein** [comment]
Hello,
From what i could see, the paths are correct. It searches for openjdk 13 dll's where it is installed.
It's worth noting it happens only on this machine, and with a local deployment of jdk13 (e.g. we install the JRE with the product that uses it)

**Comment by dorkbox** [comment]
I have added more checks + fixes for newer versions of the JDK, and this should not happen. If it continues to happen after the 4.0 release, please re-open this issue.
