### ISSUE TITLE
JNA exception on Windows when changing icon multiple times

### ISSUE THREAD

**Issue by pietrygamat** [dorkbox/SystemTray#126]
Windows 10, build 18363
JDK version 8

In the sample project I'm trying to create "animated" icon. When I change tray icon image enough times I run into the exception below. Note, it does not crash right away, but when I leave the program running for about 10 minutes, sooner or later it happens. 
Not the case for various linux desktops (using AppIndicator).

https://github.com/pietrygamat/dorkbox-crash/blob/master/src/main/java/app/Main.java

```
Exception in thread "Thread-3" ErrorCode: 0x0 [No Error]
	at dorkbox.util.jna.windows.HICONWrap.createIconIndirect(HICONWrap.java:39)
	at dorkbox.util.jna.windows.HICONWrap.<init>(HICONWrap.java:56)
	at dorkbox.systemTray.ui.swing._WindowsNativeTray.convertImage(_WindowsNativeTray.java:283)
	at dorkbox.systemTray.ui.swing._WindowsNativeTray.access$200(_WindowsNativeTray.java:57)
	at dorkbox.systemTray.ui.swing._WindowsNativeTray$1.setImage(_WindowsNativeTray.java:82)
	at dorkbox.systemTray.MenuItem.setImage_(MenuItem.java:147)
	at dorkbox.systemTray.SystemTray.setImage(SystemTray.java:1379)
	at app.Main$App.cycleFrames(Main.java:37)
	at app.Main$App.lambda$launch$1(Main.java:26)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dorkbox** [comment]
Oh interesting. I'll make sure to get for that.

Is it possible for you to share your code that is doing this?

**Comment by JockX** [comment]
> Is it possible for you to share your code that is doing this?
The full project is shared at https://github.com/JockX/dorkbox-crash

**Comment by dorkbox** [comment]
Awesome! Thanks

**Comment by dorkbox** [comment]
Did some caching and synchronization tweaks, and those changes have fixed it! 20+ minutes with no issues using your test code.

Thanks!!
