### ISSUE TITLE
NullPointerException in Ubuntu 20.04 and OpenJDK 11

### ISSUE THREAD

**Issue by bdw429s** [dorkbox/SystemTray#127]
When starting a server on **Ubuntu 20.04** and **AdoptOpenJDK 11.0.8** I have a user that gets this error in the console that prevents the app from running.  The box does have `libappindicator-dev` installed as well.

I'm aware there are some OpenJDK 11 issues with this lib, but since the error was just an NPE I wasn't sure if it was related to the Java 11 part or something else.

```
java.lang.NullPointerException
 at dorkbox.notify.Notify$3.run(Notify.java:439)
 at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
 at java.base/java.security.AccessController.doPrivileged(Native Method)
 at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
 at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
 at dorkbox.util.swing.SynchronizedEventQueue.dispatchEvent(SynchronizedEventQueue.java:51)
 at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
 at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by dorkbox** [comment]
I think this is a report for the wrong library - can you create an issue in the Notify project?

`dorkbox.notify.Notify$3.run(Notify.java:439)`

**Comment by dorkbox** [comment]
I've created an issue in the Notify project. https://github.com/dorkbox/Notify/issues/18

Thank you for reporting this.
