### ISSUE TITLE
"Serious problems! Unable to extract error image, this should NEVER happen" on multi-user system

### ISSUE THREAD

**Issue by brett-smith** [dorkbox/SystemTray#133]
I am getting this error when attempt to run the same application on two different users at the same time (using fast user switching on Linux Mint 20). It looks like the temporary directory created for system tray images is conflicting, both of them attempting to use the same location, but only the first being able to due to permissions. 

Suggest adding username or ID, so `/tmp/SystemTrayImages-myusername`. 

```
java.io.FileNotFoundException: /tmp/SystemTrayImages/D8P6V02QNUOER5J7RAEBEGQL1LVB2I89.png (Permission denied)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:347)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:261)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:216)
	at java.desktop/javax.imageio.stream.FileImageOutputStream.<init>(FileImageOutputStream.java:69)
	at java.desktop/com.sun.imageio.spi.FileImageOutputStreamSpi.createOutputStreamInstance(FileImageOutputStreamSpi.java:55)
	at java.desktop/javax.imageio.ImageIO.createImageOutputStream(ImageIO.java:419)
	at java.desktop/javax.imageio.ImageIO.write(ImageIO.java:1549)
	at SystemTray/dorkbox.systemTray.util.ImageResizeUtil.resizeFileNoCheck(ImageResizeUtil.java:241)
	at SystemTray/dorkbox.systemTray.util.ImageResizeUtil.getErrorImage(ImageResizeUtil.java:83)
	at SystemTray/dorkbox.systemTray.util.ImageResizeUtil.shouldResizeOrCache(ImageResizeUtil.java:293)
	at SystemTray/dorkbox.systemTray.SystemTray.setImage(SystemTray.java:1341)
	at uk.co.bithatch.snake.ui/uk.co.bithatch.snake.ui.tray.Tray.setImage(Tray.java:473)
	at uk.co.bithatch.snake.ui/uk.co.bithatch.snake.ui.tray.Tray.adjustTray(Tray.java:283)
	at uk.co.bithatch.snake.ui/uk.co.bithatch.snake.ui.tray.Tray.lambda$preferenceChange$27(Tray.java:533)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: Serious problems! Unable to extract error image, this should NEVER happen!
	at SystemTray/dorkbox.systemTray.util.ImageResizeUtil.getErrorImage(ImageResizeUtil.java:89)
	at SystemTray/dorkbox.systemTray.util.ImageResizeUtil.shouldResizeOrCache(ImageResizeUtil.java:293)
	at SystemTray/dorkbox.systemTray.SystemTray.setImage(SystemTray.java:1341)
	at uk.co.bithatch.snake.ui/uk.co.bithatch.snake.ui.tray.Tray.setImage(Tray.java:473)
	at uk.co.bithatch.snake.ui/uk.co.bithatch.snake.ui.tray.Tray.adjustTray(Tray.java:283)
	at uk.co.bithatch.snake.ui/uk.co.bithatch.snake.ui.tray.Tray.lambda$preferenceChange$27(Tray.java:533)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: javax.imageio.IIOException: Can't create an ImageOutputStream!
	at java.desktop/javax.imageio.ImageIO.write(ImageIO.java:1551)
	at SystemTray/dorkbox.systemTray.util.ImageResizeUtil.resizeFileNoCheck(ImageResizeUtil.java:241)
	at SystemTray/dorkbox.systemTray.util.ImageResizeUtil.getErrorImage(ImageResizeUtil.java:83)
	... 18 more


```

**Comment by dorkbox** [comment]
Fixed! Thanks for the report!
