### ISSUE TITLE
java.lang.NoClassDefFoundError: dorkbox/os/OS Exception while trying to build

### ISSUE THREAD

**Issue by maztan** [dorkbox/SystemTray#150]
Stack trace:
Caused by: java.lang.NoClassDefFoundError: dorkbox/os/OS
	at dorkbox.systemTray.SystemTray.get(SystemTray.java:216)
	at dorkbox.systemTray.SystemTray.get(SystemTray.java:170)
	at com.projecttracker.gui.TrayGui.init(TrayGui.java:50)

**Comment by maztan** [comment]
Nevermind
