### ISSUE TITLE
Exception with Maven and Modular javaFx Project

### ISSUE THREAD

**Issue by ahsand97** [dorkbox/SystemTray#158]
I'm just developing a desktop application to learn javaFx and I can't make it work with this library.

**OS: Manjaro XFCE**
I'm using Java 16, javaFx 16 and Maven

**pom.xml**

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.openjfx</groupId>
    <artifactId>hellofx</artifactId>
    <packaging>jar</packaging>
    <version>1.0-SNAPSHOT</version>
    <name>demo</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>16</maven.compiler.source>
        <maven.compiler.target>16</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>16</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.dorkbox/SystemTray -->
        <dependency>
            <groupId>com.dorkbox</groupId>
            <artifactId>SystemTray</artifactId>
            <version>4.1</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <release>16</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.6</version>
                <configuration>
                    <mainClass>org.ahsan.openjfx/org.ahsan.openjfx.MainWindow</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

**module-info.java**

```java
module org.ahsan.openjfx {

    requires transitive javafx.controls;
    requires SystemTray;

    exports org.ahsan.openjfx;
}
```

**MainWindow.java**

```java
package org.ahsan.openjfx;

import dorkbox.systemTray.SystemTray;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class MainWindow extends Application {

    @Override
    public void start(Stage stage) {
        String javaVersion = System.getProperty("java.version");
        String javafxVersion = System.getProperty("javafx.version");
        Label l = new Label("Hello, JavaFX " + javafxVersion + ", running on Java " + javaVersion + ".");
        Scene scene = new Scene(new StackPane(l), 640, 480);
        scene.getStylesheets().add("moderna_style.css");
        stage.setScene(scene);
        stage.setOnCloseRequest(event -> {
            stage.hide();
            event.consume();
        });
        try{
            crearTray();
        } catch (Throwable e) {
            e.printStackTrace();
        }
        
        stage.show();
    }

    public void crearTray() {
        SystemTray systemTray = SystemTray.get();
        if (systemTray == null) {
            throw new RuntimeException("Unable to load SystemTray!");
        }

        systemTray.installShutdownHook();
        systemTray.setImage(getClass().getResource("/tabs.png"));
    }

    @Override
    public void stop() {
        System.out.println("STOP HAS BEEN CALLED");
        Platform.exit();
        System.exit(0);
    }

    public static void main(String[] args) {
        launch();
    }

}
```
Since it is a Maven project I run it with the comand `mvn clean javafx:run` and then this exception happens:

```
java.lang.IllegalAccessError: class dorkbox.javaFx.JavaFxAccess (in unnamed module @0x293e4e27) cannot access class com.sun.javafx.tk.Toolkit (in module javafx.graphics) because module javafx.graphics does not export com.sun.javafx.tk to unnamed module @0x293e4e27
        at dorkbox.javaFx.JavaFxAccess.isEventThread(JavaFxAccess.java:33)
        at dorkbox.javaFx.JavaFx.isEventThread(JavaFx.java:146)
        at dorkbox.jna.linux.GtkEventDispatch.dispatch(GtkEventDispatch.java:277)
        at dorkbox.jna.linux.GtkEventDispatch.waitForEventsToComplete(GtkEventDispatch.java:132)
        at SystemTray@4.1/dorkbox.systemTray.SystemTray.get(SystemTray.java:643)
        at SystemTray@4.1/dorkbox.systemTray.SystemTray.get(SystemTray.java:170)
        at org.ahsan.openjfx@1.0-SNAPSHOT/org.ahsan.openjfx.MainWindow.crearTray(MainWindow.java:44)
        at org.ahsan.openjfx@1.0-SNAPSHOT/org.ahsan.openjfx.MainWindow.start(MainWindow.java:35)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:474)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:447)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:446)
        at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
        at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
        at java.base/java.lang.Thread.run(Thread.java:831)
```

I already put args on the **maven-compiler-plugin** in the **pom.xml**  with the `--add-exports` option
```xml
<configuration>
    <compilerArgs>
        <arg>--add-exports</arg>
        <arg>javafx.graphics/com.sun.javafx.tk=ALL-UNNAMED</arg>
    </compilerArgs>
</configuration>
```
and it did nothing, also like this:
```xml
<configuration>
    <compilerArgs>
        <arg>--add-exports</arg>
        <arg>javafx.graphics/com.sun.javafx.tk=SystemTray</arg>
    </compilerArgs>
</configuration>
```
But I don't seems to work, can't run the app or create the tray icon.

**Comment by ahsand97** [comment]
If anyone come across this issue I solver by adding this to the **pom.xml** file to make it work:

```xml
<plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.8.1</version>
            <configuration>
                <release>16</release>
                <compilerArgs>
                    <arg>--add-exports</arg>
                    <arg>javafx.graphics/com.sun.javafx.tk=ALL-UNNAMED</arg>
                </compilerArgs>
            </configuration>
        </plugin>
        <plugin>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-maven-plugin</artifactId>
            <version>0.0.6</version>
            <configuration>
                <options>
                    <option>--add-exports</option>
                    <arg>javafx.graphics/com.sun.javafx.tk=ALL-UNNAMED</arg>
                </options>
                <mainClass>org.ahsan.openjfx/org.ahsan.openjfx.MainWindow</mainClass>
            </configuration>
        </plugin>
    </plugins>
```

By adding the **--add-exports** arg in compile and runtime the tray icon works.
