### ISSUE TITLE
Unable to use on Mac with enabled AUTO_FIX_INCONSISTENCIES

### ISSUE THREAD

**Issue by basix86** [dorkbox/SystemTray#189]
When I create the tray icon on mac in retrive this stack trace:

`Exception in thread "AWT-EventQueue-0" java.lang.LinkageError: loader 'bootstrap' attempted duplicate class definition for java.awt.TrayIcon. (java.awt.TrayIcon is in module java.desktop of loader 'bootstrap')
	at com.sun.jna.Native.invokeVoid(Native Method)
	at com.sun.jna.Function.invoke(Function.java:415)
	at com.sun.jna.Function.invoke(Function.java:361)
	at com.sun.jna.Library$Handler.invoke(Library.java:265)
	at com.sun.proxy.$Proxy6.JVM_DefineClass(Unknown Source)
	at dorkbox.jna.ClassUtils.defineClass(ClassUtils.java:123)
	at dorkbox.systemTray.util.SystemTrayFixesMacOS.fix(SystemTrayFixesMacOS.java:102)
	at dorkbox.systemTray.SystemTray.get(SystemTray.java:748)`
	
The error is generated from the calls:
`ClassUtils.defineClass(null, trayIconClass.toBytecode());` that not allow to overwrite TrayIcon in the classloader.

As workaround I have disabled the AUTO_FIX_INCONSISTENCIES

PS: I'm using Temurin JDK 11 and MacOsX 13.2.1

**Comment by dorkbox** [comment]
This is fixed in the (not yet released) version 4.5
