### ISSUE TITLE
Runtime Libs

### ISSUE THREAD

**Issue by gmseed** [dorkbox/SystemTray#192]
I get numerous runtime exception when running SystemTray. Why doesn't the Maven jar package everything it needs?

Some example of runtime exceptions:

Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/jvm/internal/Reflection
        at dorkbox.updates.Updates.<clinit>(Updates.kt:25)
        at dorkbox.os.OS.<clinit>(OS.kt:34)
        at dorkbox.systemTray.SystemTray.<clinit>(SystemTray.java:101)
        at qis.SystrayIcon.<init>(SystrayIcon.java:44)
        at qis.qisMain.main(qisMain.java:173)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Reflection
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 5 more

Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jna/win32/W32APIOptions
        at dorkbox.jna.JNA.register(JNA.java:54)
        at dorkbox.jna.windows.User32_64.<clinit>(User32_64.java:47)
        at dorkbox.jna.windows.User32.<clinit>(User32.java:40)
        at dorkbox.systemTray.util.SizeAndScalingWindows.getTrayImageSize(SizeAndScalingWindows.java:89)
        at dorkbox.systemTray.util.SizeAndScaling.getTrayImageSize(SizeAndScaling.java:56)
        at dorkbox.systemTray.SystemTray.get(SystemTray.java:707)
        at dorkbox.systemTray.SystemTray.get(SystemTray.java:171)
        
[main] ERROR dorkbox.systemTray.SystemTray - Unable to create tray type: '_WindowsNativeTray'
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at dorkbox.systemTray.SystemTray.get(SystemTray.java:799)
        at dorkbox.systemTray.SystemTray.get(SystemTray.java:171)

**Comment by dorkbox** [comment]
This is meant as a library (not an application) so I don’t release a fat-jar, and depending on your system — the dependencies can be different. 

You can see the list of them here:
https://github.com/dorkbox/SystemTray/blob/ea23b1da81bd540c4d28ed718e1be19a77173d2e/build.gradle.kts#L182
