### ISSUE TITLE
Module org.javassist not found, required by dorkbox.systemtray

### ISSUE THREAD

**Issue by smallclover** [dorkbox/SystemTray#200]
The following error occurred when I ran this command [mvn install], But the jar [javassist] is indeed in the lib directory.

Java Version:JDK21

```log
 Building jar: D:\IdeaProjects\abc\target\abc-1.5.6-runnable.jar
[INFO]     Runnable jar created in D:\IdeaProjects\abc\target\abc-1.5.6-runnable.jar!
[INFO]     
[INFO]     Bundling JRE ... with C:\Users\xxx\.jdks\openjdk-21.0.1
[INFO]         Creating customized JRE ...
[INFO]         Getting required modules ... 
[INFO]             Executing command: cmd.exe /s /c "C:\Users\xxx\.jdks\openjdk-21.0.1\bin\jdeps -q --multi-release 21 --ignore-missing-deps --print-module-deps D:\IdeaProjects\abc\target\abc\libs\*.jar D:\IdeaProjects\abc\target\abc-1.5.6-runnable.jar"
[ERROR]             Exception in thread "main" java.lang.module.FindException: Module org.javassist not found, required by dorkbox.systemtray
[ERROR]             	at java.base/java.lang.module.Resolver.findFail(Resolver.java:892)
[ERROR]             	at java.base/java.lang.module.Resolver.resolve(Resolver.java:192)
[ERROR]             	at java.base/java.lang.module.Resolver.resolve(Resolver.java:141)
[ERROR]             	at java.base/java.lang.module.Configuration.resolve(Configuration.java:420)
[ERROR]             	at java.base/java.lang.module.Configuration.resolve(Configuration.java:254)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsConfiguration$Builder.build(JdepsConfiguration.java:564)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.buildConfig(JdepsTask.java:607)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:561)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.JdepsTask.run(JdepsTask.java:537)
[ERROR]             	at jdk.jdeps/com.sun.tools.jdeps.Main.main(Main.java:50)
```

**Comment by dorkbox** [comment]
You have to be a bit careful how you add dependencies on the module-path - it’s not automatic. It’s likely that something else is adding things in an unexpected way.
