### ISSUE TITLE
Exception on Ubuntu 22.04

### ISSUE THREAD

**Issue by gmseed** [dorkbox/SystemTray#210]
Hi

I've been using Dorkbox's SystemTray for some time on Ubuntu and Mint and worked fine, but now a user using Ubuntu 22.04 is reporting that it's throwing exceptions:

stderr: [main] WARN dorkbox.systemTray.SystemTray - Attempting to load the SystemTray as the 'root/sudo' user. This will likely not work because of dbus restrictions. Using the Swing Tray type instead. Please refer to the readme notes or issue #63 on how to work around this.
stderr: [AWT-EventQueue-0] ERROR dorkbox.systemTray.SystemTray - Unable to create tray type: '_SwingTray'
stderr: java.lang.reflect.InvocationTargetException
...
stderr: Caused by: java.lang.RuntimeException: System Tray is not supported in this configuration! Please write an issue and include your OS type and configuration
stderr: at dorkbox.systemTray.ui.swing._SwingTray.<init>(_SwingTray.java:71)
stderr: ... 19 more
stderr: [main] ERROR dorkbox.systemTray.SystemTray - Unable to create tray type: '_SwingTray'
...

**Comment by asfdnkw** [comment]
Hello. I am using SystemTray on the ubantu2204 Java 8 application. An error occurred while running this code.
SystemTray systemTray = SystemTray.get();



Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: dorkbox/util/OSUtil$DesktopEnv
	at dorkbox.jna.linux.GtkTheme.getIndicatorSize(GtkTheme.java:232)
	at dorkbox.systemTray.util.SizeAndScalingLinux.getTrayImageSize(SizeAndScalingLinux.java:55)
	at dorkbox.systemTray.util.SizeAndScaling.getTrayImageSize(SizeAndScaling.java:50)
	at dorkbox.systemTray.SystemTray.get(SystemTray.java:707)
	at dorkbox.systemTray.SystemTray.get(SystemTray.java:171)

I guess the reason is the lack of jar package. But I can't find this jar package. Can you provide me with some help? Thank you
