### ISSUE TITLE
Windows TrayPopup pop-up error.

### ISSUE THREAD

**Issue by westboy** [dorkbox/SystemTray#214]
windows 10 TrayPopup pops up an error, but it works normally under windows 11.

> 2024-07-16 15:38:35 ERROR org.dromara.quickswing.QSApplicationInitializer:57 - Thread AWT-EventQueue-0 
> java.lang.NullPointerException: Cannot read field "y" because "bounds" is null
> 	at dorkbox.systemTray.ui.swing.TrayPopup.doShow(TrayPopup.java:126)
> 	at dorkbox.systemTray.ui.swing._SwingTray$1$1.mousePressed(_SwingTray.java:168)
> 	at java.desktop/java.awt.TrayIcon.processMouseEvent(Unknown Source)
> 	at java.desktop/java.awt.TrayIcon.processEvent(Unknown Source)
> 	at java.desktop/java.awt.TrayIcon.dispatchEvent(Unknown Source)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
> 	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
> 	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
> 	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
> 	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
> 	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
> 	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> 	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by westboy** [comment]
The calculation result under WIN10 is infinite
![1721151009462](https://github.com/user-attachments/assets/618e0085-5420-4998-b4a8-7e8debf879cd)

**Comment by westboy** [comment]
Extracting Chinese or other non Latin language Windows operating systems in this way will cause problems
![image](https://github.com/user-attachments/assets/9b94eb06-e666-4f46-a816-745535eafe56)

**Comment by asfdnkw** [comment]
I posted a question in # 215. Can you give me some help
