### ISSUE TITLE
Error using latest beta with JavaFX and Gnome 3

### ISSUE THREAD

**Issue by ashyon** [dorkbox/SystemTray#26]
```
/usr/lib/jvm/default/bin/java -Didea.launcher.port=7535 -Didea.launcher.bin.path=/usr/share/intellijidea-ce/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/default/lib/ant-javafx.jar:/usr/lib/jvm/default/jre/lib/charsets.jar:/usr/lib/jvm/default/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/default/jre/lib/ext/dnsns.jar:/usr/lib/jvm/default/jre/lib/ext/jaccess.jar:/usr/lib/jvm/default/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/default/jre/lib/ext/localedata.jar:/usr/lib/jvm/default/jre/lib/ext/nashorn.jar:/usr/lib/jvm/default/jre/lib/ext/sunec.jar:/usr/lib/jvm/default/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/default/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/default/jre/lib/ext/zipfs.jar:/usr/lib/jvm/default/jre/lib/jce.jar:/usr/lib/jvm/default/jre/lib/jfxswt.jar:/usr/lib/jvm/default/jre/lib/jsse.jar:/usr/lib/jvm/default/jre/lib/management-agent.jar:/usr/lib/jvm/default/jre/lib/resources.jar:/usr/lib/jvm/default/jre/lib/rt.jar:/home/ash/Projects/IdeaProjects/emojikeyboard-java/build/classes/main:/home/ash/Projects/IdeaProjects/emojikeyboard-java/build/resources/main:/home/ash/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.7/751f548c85fa49f330cecbb1875893f971b33c4e/gson-2.7.jar:/home/ash/.gradle/caches/modules-2/files-2.1/commons-collections/commons-collections/3.2.2/8ad72fe39fa8c91eaaf12aadb21e0c3661fe26d5/commons-collections-3.2.2.jar:/home/ash/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-core/6.2.1/a1d9ed9e06072fefa13b070628269ccc0a90d7cc/lucene-core-6.2.1.jar:/home/ash/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-lang3/3.4/5fe28b9518e58819180a43a850fbc0dd24b7c050/commons-lang3-3.4.jar:/home/ash/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-analyzers-common/6.2.1/8e08c604b610cdb91b898c841e8a8254b0f020dc/lucene-analyzers-common-6.2.1.jar:/home/ash/Projects/IdeaProjects/emojikeyboard-java/libs/SystemTray_v2.20_normal.jar:/usr/share/intellijidea-ce/lib/idea_rt.jar com.intellij.rt.execution.application.AppMain net.ashyon.emojikeyboard.Main
09:51:52.544 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - is JavaFX detected? true
09:51:52.549 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - is SWT detected? false
09:51:52.549 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - is using native menus? false
09:51:52.551 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Auto-detecting tray type
09:51:52.551 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - FORCE_GTK2: true
09:51:52.599 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - GTK: gtk-x11-2.0
09:51:52.599 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Is the system already running GTK? true
09:51:52.599 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Loading libraries
09:51:52.630 [JavaFX Application Thread] ERROR dorkbox.systemTray.SystemTray - Auto-detected that gnome-shell is running
09:51:52.631 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Currently using the 'gnome' desktop
09:51:52.631 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Currently using the 'gnome' session type
09:51:52.661 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Installing gnome-shell extension
09:51:52.682 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Checking current version of extension for upgrade
09:51:52.683 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - DEBUG mode enabled. You need to manually restart the shell via 'gnome-shell --replace &'
09:51:52.703 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Checking scaling factor for GTK environment, should start with 'uint32', value: 'uint32 0
'
09:51:52.963 [AWT-EventQueue-0] ERROR dorkbox.systemTray.SystemTray - Cannot initialize JavaFX
java.lang.NoSuchMethodException: javafx.application.Platform.runLater()
	at java.lang.Class.getMethod(Class.java:1786)
	at dorkbox.systemTray.util.JavaFX.dispatch(JavaFX.java:42)
	at dorkbox.systemTray.linux.jna.Gtk.dispatch(Gtk.java:310)
	at dorkbox.systemTray.swingUI._GtkStatusIconTray.<init>(_GtkStatusIconTray.java:88)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at dorkbox.systemTray.SystemTray$1.run(SystemTray.java:595)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
09:51:52.963 [AWT-EventQueue-0] ERROR dorkbox.systemTray.SystemTray - Unable to execute JavaFX runLater(). Please create an issue with your OS and Java version so we may further investigate this issue.
09:51:52.964 [AWT-EventQueue-0] ERROR dorkbox.systemTray.SystemTray - Cannot initialize JavaFX
java.lang.NoSuchMethodException: javafx.application.Platform.runLater()
	at java.lang.Class.getMethod(Class.java:1786)
	at dorkbox.systemTray.util.JavaFX.dispatch(JavaFX.java:42)
	at dorkbox.systemTray.linux.jna.Gtk.dispatch(Gtk.java:310)
	at dorkbox.systemTray.linux.jna.Gtk.waitForStartup(Gtk.java:224)
	at dorkbox.systemTray.swingUI._GtkStatusIconTray.<init>(_GtkStatusIconTray.java:116)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at dorkbox.systemTray.SystemTray$1.run(SystemTray.java:595)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
09:51:52.964 [AWT-EventQueue-0] ERROR dorkbox.systemTray.SystemTray - Unable to execute JavaFX runLater(). Please create an issue with your OS and Java version so we may further investigate this issue.
09:52:03.066 [AWT-EventQueue-0] ERROR dorkbox.systemTray.SystemTray - Cannot initialize JavaFX
java.lang.NoSuchMethodException: javafx.application.Platform.runLater()
	at java.lang.Class.getMethod(Class.java:1786)
	at dorkbox.systemTray.util.JavaFX.dispatch(JavaFX.java:42)
	at dorkbox.systemTray.linux.jna.Gtk.dispatch(Gtk.java:310)
	at dorkbox.systemTray.swingUI._GtkStatusIconTray.<init>(_GtkStatusIconTray.java:119)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at dorkbox.systemTray.SystemTray$1.run(SystemTray.java:595)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
09:52:03.066 [AWT-EventQueue-0] ERROR dorkbox.systemTray.SystemTray - Unable to execute JavaFX runLater(). Please create an issue with your OS and Java version so we may further investigate this issue.
09:52:03.066 [AWT-EventQueue-0] INFO dorkbox.systemTray.SystemTray - Successfully Loaded: _GtkStatusIconTray

(java:19956): Gtk-CRITICAL **: IA__gtk_status_icon_set_from_file: assertion 'GTK_IS_STATUS_ICON (status_icon)' failed

(java:19956): Gtk-CRITICAL **: IA__gtk_status_icon_set_visible: assertion 'GTK_IS_STATUS_ICON (status_icon)' failed

```

**Comment by dorkbox** [comment]
what version of java is this running? the error is saying javafx cannot be initialized.

**Comment by ashyon** [comment]
It's running with Java 8. It works fine with the SystemTray version from Maven

**Comment by dorkbox** [comment]
Ah hah!  This is a regression from getting native menus working. Thanks for the report, i'll have a fix shortly.

**Comment by dorkbox** [comment]
This should now be fixed. Updated Beta jars are on [my server](https://files2.dorkbox.com/SystemTray_autodetect/).

**Comment by dorkbox** [comment]
(fun bit of trivial, JavaFX cannot be initialized from the Swing EDT)
