### ISSUE TITLE
menu is not instanceof _GtkStatusIconNativeTray?

### ISSUE THREAD

**Issue by ashyon** [dorkbox/SystemTray#31]
When I call shutdown() on the SystemTray, it throws a NullPointerException. A stacktrace shows that it was trying to call ((_SwingTray)menu).shutdown(), but the log says it should be calling ((_GtkStatusIconNativeTray)menu).shutdown(), as it is recognized as that type of tray. Dunno why it's not that type of tray, but yeah.

```
/usr/lib/jvm/default/bin/java -Didea.launcher.port=7534 -Didea.launcher.bin.path=/usr/share/intellijidea-ce/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/default/jre/lib/charsets.jar:/usr/lib/jvm/default/jre/lib/deploy.jar:/usr/lib/jvm/default/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/default/jre/lib/ext/dnsns.jar:/usr/lib/jvm/default/jre/lib/ext/jaccess.jar:/usr/lib/jvm/default/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/default/jre/lib/ext/localedata.jar:/usr/lib/jvm/default/jre/lib/ext/nashorn.jar:/usr/lib/jvm/default/jre/lib/ext/sunec.jar:/usr/lib/jvm/default/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/default/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/default/jre/lib/ext/zipfs.jar:/usr/lib/jvm/default/jre/lib/javaws.jar:/usr/lib/jvm/default/jre/lib/jce.jar:/usr/lib/jvm/default/jre/lib/jfr.jar:/usr/lib/jvm/default/jre/lib/jfxswt.jar:/usr/lib/jvm/default/jre/lib/jsse.jar:/usr/lib/jvm/default/jre/lib/management-agent.jar:/usr/lib/jvm/default/jre/lib/plugin.jar:/usr/lib/jvm/default/jre/lib/resources.jar:/usr/lib/jvm/default/jre/lib/rt.jar:/usr/lib/jvm/default/lib/ant-javafx.jar:/home/ash/Projects/IdeaProjects/emojikeyboard-java/build/classes/main:/home/ash/Projects/IdeaProjects/emojikeyboard-java/build/resources/main:/home/ash/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.7/751f548c85fa49f330cecbb1875893f971b33c4e/gson-2.7.jar:/home/ash/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-analyzers-common/6.2.1/8e08c604b610cdb91b898c841e8a8254b0f020dc/lucene-analyzers-common-6.2.1.jar:/home/ash/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-lang3/3.4/5fe28b9518e58819180a43a850fbc0dd24b7c050/commons-lang3-3.4.jar:/home/ash/.gradle/caches/modules-2/files-2.1/org.apache.lucene/lucene-core/6.2.1/a1d9ed9e06072fefa13b070628269ccc0a90d7cc/lucene-core-6.2.1.jar:/home/ash/.gradle/caches/modules-2/files-2.1/commons-collections/commons-collections/3.2.2/8ad72fe39fa8c91eaaf12aadb21e0c3661fe26d5/commons-collections-3.2.2.jar:/home/ash/Projects/IdeaProjects/emojikeyboard-java/libs/SystemTray_v2.20_normal.jar:/usr/share/intellijidea-ce/lib/idea_rt.jar com.intellij.rt.execution.application.AppMain net.ashyon.emojikeyboard.Main
Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `gtk-primary-button-warps-slider' of type `gboolean' from rc file value "((GString*) 0x7f55780a06e0)" of type `gboolean'
09:58:34.098 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - OS: Linux
09:58:34.102 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Arch: amd64
09:58:34.102 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - is AutoTraySize? true
09:58:34.102 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - is JavaFX detected? true
09:58:34.102 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - is SWT detected? false
09:58:34.102 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - is using native menus? true
09:58:34.104 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Forcing GTK2 because JavaFX is GTK2
09:58:34.104 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Auto-detecting tray type
09:58:34.104 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - FORCE_GTK2: true
09:58:34.162 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - GTK: gtk-x11-2.0
09:58:34.162 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Is the system already running GTK? true
09:58:34.162 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Loading libraries
09:58:34.188 [JavaFX Application Thread] ERROR dorkbox.systemTray.SystemTray - Auto-detected that gnome-shell is running
09:58:34.188 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Currently using the 'gnome' desktop
09:58:34.189 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Currently using the 'gnome-xorg' session type
09:58:34.213 [JavaFX Application Thread] ERROR dorkbox.systemTray.SystemTray - Unable to load the system tray native library. Please write an issue and include your OS type and configuration
09:58:34.225 [JavaFX Application Thread] DEBUG dorkbox.systemTray.SystemTray - Checking scaling factor for GTK environment, should start with 'uint32', value: 'uint32 0
'
09:58:34.278 [JavaFX Application Thread] INFO dorkbox.systemTray.SystemTray - Successfully Loaded: _GtkStatusIconNativeTray
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at dorkbox.systemTray.SystemTray.shutdown(SystemTray.java:697)
	at dorkbox.systemTray.SystemTray$2.run(SystemTray.java:611)
	at com.sun.javafx.tk.Toolkit.notifyShutdownHooks(Toolkit.java:476)
	at com.sun.javafx.tk.quantum.QuantumToolkit.exit(QuantumToolkit.java:756)
	at com.sun.javafx.application.PlatformImpl.lambda$tkExit$178(PlatformImpl.java:450)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by dorkbox** [comment]
Ah. Rats.... I know what it is. I've been working on it so that shutdown()
cleans up enough after itself so that one can recreate the system tray
without problems. You can ignore that error for now, and I'll have that
finished tonight.

Thanks for the report.

**Comment by dorkbox** [comment]
Fixed issue with shutdown + tray types + several other issues.  Latest jars are on my server.
