### ISSUE TITLE
ChromeOS Support

### ISSUE THREAD

**Issue by tresf** [dorkbox/SystemTray#52]
[Java 8 can run on ChromeOS](http://www.meetchrome.com/java-on-chromebook/), but the dorkbox GTK detection seems to be broken... 

```
Caused by: java.lang.RuntimeException: We apologize for this, but we are unable to determine
the GTK library is in use, or even if it is in use... Please create an issue for this and include
your OS type and configuration.
        at dorkbox.systemTray.jna.linux.Gtk.<clinit>(Gtk.java:200)
        ... 17 more
```

Pre-built Chrome OS is available for VirtualBox here: http://go.neverware.com/freeVirtualbox.  Installing Java is a manual and somewhat tricky process, but it seems to work.

**Comment by dorkbox** [comment]
Unfortunately, it won't work on ChromeOS. There are no GTK libraries on the system, and Swing cannot create a native peer via X11. I've added detection methods so that an error will be emitted (instead of exceptions while trying to load Swing/libraries). Also updated the readme to reflect this.

**Comment by pravya191** [comment]
Exception in thread "main" java.lang.ExceptionInInitializerError
	at dorkbox.util.jna.linux.GtkEventDispatch.startGui(GtkEventDispatch.java:79)
	at dorkbox.systemTray.SystemTray.init(SystemTray.java:844)
	at dorkbox.systemTray.SystemTray.get(SystemTray.java:1077)
	at systemtray.TestTray.<init>(TestTray.java:62)
	at systemtray.TestTray.main(TestTray.java:48)
Caused by: java.lang.RuntimeException: We apologize for this, but we are unable to determine the GTK library is in use, or even if it is in use... Please create an issue for this and include your OS type and configuration.
	at dorkbox.util.jna.linux.GtkLoader.<clinit>(GtkLoader.java:243)

**Comment by dorkbox** [comment]
It appears that ChromeOS has changed how to identify their OS. Can you enable `SystemTray.DEBUG` and paste the output of that?
