### ISSUE TITLE
NullPointerException at dorkbox.util.OSUtil$DesktopEnv.isChromeOS(OSUtil.java:732)

### ISSUE THREAD

**Issue by cmaulini** [dorkbox/SystemTray#64]
The dorkbox SystemTray 3.7 don't work on Ubuntu MATE (16.04).

```
Caused by: java.lang.NullPointerException
	at dorkbox.util.OSUtil$DesktopEnv.isChromeOS(OSUtil.java:732)
	at dorkbox.util.OSUtil$DesktopEnv.get(OSUtil.java:465)
	at dorkbox.systemTray.SystemTray.init(SystemTray.java:715)
	at dorkbox.systemTray.SystemTray.get(SystemTray.java:1017)`
```

`System.getenv("XDG_CURRENT_DESKTOP")` returns `"MATE"`.
`dorkbox.util.OSUtil.DesktopEnv.get()` calls `dorkbox.util.OSUtil.DesktopEnv.isChromeOS()`,
`ps aux` doesn't contains `"chromeos"` and `isChromeOs` variable never initialized.

Debug info:
```
2017-09-22 08:49:08.150 - DEBUG -  -- [            main] dorkbox.systemTray.SystemTray            : OS: Linux
2017-09-22 08:49:08.333 - DEBUG -  -- [            main] dorkbox.systemTray.SystemTray            : Arch: i386
2017-09-22 08:49:08.948 - DEBUG -  -- [            main] dorkbox.systemTray.SystemTray            : Oracle Corporation Java HotSpot(TM) Client VM 1.8.0_74
2017-09-22 08:49:09.122 - DEBUG -  -- [            main] dorkbox.systemTray.SystemTray            : Is Auto sizing tray/menu? true
2017-09-22 08:49:09.308 - DEBUG -  -- [            main] dorkbox.systemTray.SystemTray            : Is JavaFX detected? false
2017-09-22 08:49:09.610 - DEBUG -  -- [            main] dorkbox.systemTray.SystemTray            : Is SWT detected? false
2017-09-22 08:49:09.905 - DEBUG -  -- [            main] dorkbox.systemTray.SystemTray            : Java Swing L&F: JGoodies Plastic XP
2017-09-22 08:49:10.703 - DEBUG -  -- [            main] dorkbox.systemTray.SystemTray            : Auto-detecting tray type
2017-09-22 08:49:11.305 - DEBUG -  -- [            main] dorkbox.systemTray.SystemTray            : Force GTK2: false
2017-09-22 08:49:11.826 - DEBUG -  -- [            main] dorkbox.systemTray.SystemTray            : Prefer GTK3: true
```

**Comment by dorkbox** [comment]
Thanks for the report!

Fixed in 3.8 via https://github.com/dorkbox/Utilities/commit/8ca60fce7320bcb92a6f84be28cd6d2c4c6585b4
