### ISSUE TITLE
Running program with root rights

### ISSUE THREAD

**Issue by Djaler** [dorkbox/SystemTray#70]
When I try to run my program with root rights, I get this stacktrace
`2017-11-21 17:23:59 ERROR SystemTray:921 - Unable to create tray type: '_SwingTray'
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at dorkbox.systemTray.SystemTray.init(SystemTray.java:919)
	at dorkbox.systemTray.SystemTray.get(SystemTray.java:1018)
	at org.communis.ca.desktop.Main.initTray(Main.java:245)
	at org.communis.ca.desktop.Main.init(Main.java:95)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:841)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: System Tray is not supported in this configuration! Please write an issue and include your OS type and configuration
	at dorkbox.systemTray.ui.swing._SwingTray.<init>(_SwingTray.java:60)
	... 11 more
`
After that SystemTray is not null, but systemTray.getMenu() is null

Library version: 3.11
Java vesion: 8
OS: elementary OS Loki (based on Ubuntu 16.04)

**Comment by dorkbox** [comment]
So the tray *really* doesn't like running as root unless you do some magic... See this post for more info: https://github.com/dorkbox/SystemTray/issues/63#issuecomment-330619409

I'll go ahead and close this, but re-open it (please!) if you encounter further issues.
