### ISSUE TITLE
Java 9 issue

### ISSUE THREAD

**Issue by kaloyan-raev** [dorkbox/SystemTray#72]
I have the following issue on Windows 10 with Java 9:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by dorkbox.systemTray.util.SystemTrayFixes (file:/C:/Users/meije/Downloads/goobox-sync-storj-0.0.9-win64/goobox-sync-storj/goobox-sync-storj-0.0.9.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
WARNING: Please consider reporting this to the maintainers of dorkbox.systemTray.util.SystemTrayFixes
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
21:44:53.803 [main] ERROR dorkbox.systemTray.SystemTray - Error setting tray icon size to: 40
javassist.NotFoundException: sun.awt.windows.WSystemTrayPeer
        at javassist.ClassPool.get(ClassPool.java:452)
        at dorkbox.systemTray.util.SystemTrayFixes.fixWindows(SystemTrayFixes.java:142)
        at dorkbox.systemTray.SystemTray.init(SystemTray.java:905)
        at dorkbox.systemTray.SystemTray.get(SystemTray.java:1039)
        at io.goobox.sync.common.systemtray.SystemTrayHelper.init(SystemTrayHelper.java:89)
        at io.goobox.sync.common.systemtray.SystemTrayHelper.initialized(SystemTrayHelper.java:127)
        at io.goobox.sync.common.systemtray.SystemTrayHelper.setIdle(SystemTrayHelper.java:51)
        at io.goobox.sync.storj.App.init(App.java:68)
        at io.goobox.sync.storj.App.main(App.java:44)
21:44:53.956 [main] INFO dorkbox.systemTray.SystemTray - Successfully loaded
21:44:54.001 [main] WARN dorkbox.systemTray.SystemTray - Tooltips are not consistent across all platforms and tray types.
```

It seems the reflection does not work. As result, the tray icon is not autosized and the items in the context menu look bigger.

No such issue with Java 8.

**Comment by dorkbox** [comment]
I have a windows API implementation for a system tray I will swap in. Before this is fully resolved, I will have to build a MACOS implementation as well. Not impossible, just a bit of work.

**Comment by dorkbox** [comment]
There is now a native MacOS implementation (java -> objective-c was interesting...), revision: 4d9e0479a59ad177216b6e712d9936663b9b061a.  As such, unless you explicitly specify AWT or Swing, the system tray fixes using reflection will not happen (and thus, no issues with java 9+).

There might be other java9+/jigsaw issues, but reflection should no longer be one of them.
