### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by DiWizard** [dorkbox/SystemTray#79]
Hi! Sorry for stupid question... Is SystemTray library compatible with Raspberry Pi or not?

**Comment by dorkbox** [comment]
Not a stupid question at all. I have not tested it on any ARM devices, but it should be.

**Comment by DiWizard** [comment]
My pi-box is "Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux"

TestTray.java result:
[main] ERROR dorkbox.util.jna.linux.GtkLoader - Error loading library.
java.lang.UnsatisfiedLinkError: /tmp/jna-3577/jna818880273196706368.tmp: /tmp/jna-3577/jna818880273196706368.tmp: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:947)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:96)
	at dorkbox.util.jna.JnaHelper.register(JnaHelper.java:47)
	at dorkbox.util.jna.linux.GtkLoader.<clinit>(GtkLoader.java:133)
	at dorkbox.util.jna.linux.GtkEventDispatch.startGui(GtkEventDispatch.java:78)
	at dorkbox.systemTray.SystemTray.init(SystemTray.java:813)
	at dorkbox.systemTray.SystemTray.get(SystemTray.java:1039)
	at dorkbox.TestTray.<init>(TestTray.java:80)
	at dorkbox.TestTray.main(TestTray.java:63)
[main] ERROR dorkbox.util.jna.linux.GtkLoader - Error loading library
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.NativeLibrary
	at dorkbox.util.jna.JnaHelper.register(JnaHelper.java:47)
	at dorkbox.util.jna.linux.GtkLoader.<clinit>(GtkLoader.java:169)
	at dorkbox.util.jna.linux.GtkEventDispatch.startGui(GtkEventDispatch.java:78)
	at dorkbox.systemTray.SystemTray.init(SystemTray.java:813)
	at dorkbox.systemTray.SystemTray.get(SystemTray.java:1039)
	at dorkbox.TestTray.<init>(TestTray.java:80)
	at dorkbox.TestTray.main(TestTray.java:63)
Exception in thread "main" java.lang.ExceptionInInitializerError
	at dorkbox.util.jna.linux.GtkEventDispatch.startGui(GtkEventDispatch.java:78)
	at dorkbox.systemTray.SystemTray.init(SystemTray.java:813)
	at dorkbox.systemTray.SystemTray.get(SystemTray.java:1039)
	at dorkbox.TestTray.<init>(TestTray.java:80)
	at dorkbox.TestTray.main(TestTray.java:63)
Caused by: java.lang.RuntimeException: We apologize for this, but we are unable to determine the GTK library is in use, or even if it is in use... Please create an issue for this and include your OS type and configuration.
	at dorkbox.util.jna.linux.GtkLoader.<clinit>(GtkLoader.java:241)
	... 5 more

TestTray.java with System.setProperty("SWT_GTK3", "0"); SystemTray.FORCE_GTK2=true; result:
[main] ERROR dorkbox.util.jna.linux.GtkLoader - Error loading library
java.lang.UnsatisfiedLinkError: /tmp/jna-3577/jna7875446416049634230.tmp: /tmp/jna-3577/jna7875446416049634230.tmp: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1938)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1821)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:947)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:96)
	at dorkbox.util.jna.JnaHelper.register(JnaHelper.java:47)
	at dorkbox.util.jna.linux.GtkLoader.<clinit>(GtkLoader.java:93)
	at dorkbox.util.jna.linux.GtkEventDispatch.startGui(GtkEventDispatch.java:78)
	at dorkbox.systemTray.SystemTray.init(SystemTray.java:813)
	at dorkbox.systemTray.SystemTray.get(SystemTray.java:1039)
	at dorkbox.TestTray.<init>(TestTray.java:80)
	at dorkbox.TestTray.main(TestTray.java:63)
Exception in thread "GTK Native Event Loop" java.lang.UnsatisfiedLinkError: dorkbox.util.jna.linux.Gtk3.gtk_init_check(I)Z
	at dorkbox.util.jna.linux.Gtk3.gtk_init_check(Native Method)
	at dorkbox.util.jna.linux.GtkEventDispatch$2.run(GtkEventDispatch.java:96)
Exception in thread "main" java.lang.UnsatisfiedLinkError: dorkbox.util.jna.linux.Gtk3.g_main_context_invoke(Ldorkbox/util/jna/linux/GMainContext;Ldorkbox/util/jna/linux/FuncCallback;Lcom/sun/jna/Pointer;)V
	at dorkbox.util.jna.linux.Gtk3.g_main_context_invoke(Native Method)
	at dorkbox.util.jna.linux.GtkEventDispatch.dispatch(GtkEventDispatch.java:326)
	at dorkbox.util.jna.linux.GtkEventDispatch.waitForEventsToComplete(GtkEventDispatch.java:129)
	at dorkbox.systemTray.SystemTray.init(SystemTray.java:814)
	at dorkbox.systemTray.SystemTray.get(SystemTray.java:1039)
	at dorkbox.TestTray.<init>(TestTray.java:80)
	at dorkbox.TestTray.main(TestTray.java:63)

P.S. The same jar-file under Windows/MacOS/Ubuntu/Kubuntu/Lubuntu (all x86-64) works well.

**Comment by dorkbox** [comment]
The SystemTray uses JNA for creating the tray icon -- so it is likely the wrong type of ARM cpu. I know JNA supports ARM, but I don't know exactly which one (eg: hard float vs soft float CPU).

If you do end up getting a version of JNA to work, can you share the details? This way I can post instructions in the readme for others to follow.

**Comment by DiWizard** [comment]
Ok. Thank you for replay. I will try to understand this problem...

**Comment by dorkbox** [comment]
No worries. It might not be a solvable problems, because the JNA binaries just might not exist.

**Comment by DiWizard** [comment]
Well, it was my fault. In fact on Raspbian 4.9 I should use exactly JNA 4.0.0 library instead JNA 5.2.0 or any other I tried to use.
