### ISSUE TITLE
"WSystemTrayPeer class is frozen" while setting tooltip / calling from custom gradle plugin

### ISSUE THREAD

**Issue by pun-ky** [dorkbox/SystemTray#85]
```
Error setting tray icon size to: 16
java.lang.RuntimeException: sun.awt.windows.WSystemTrayPeer class is frozen
        at javassist.CtClassType.checkModify(CtClassType.java:309)
        at javassist.CtClassType.setModifiers(CtClassType.java:465)
        at dorkbox.systemTray.util.SystemTrayFixes.fixWindows(SystemTrayFixes.java:145)
        at dorkbox.systemTray.SystemTray.init(SystemTray.java:905)
        at dorkbox.systemTray.SystemTray.get(SystemTray.java:1039)


```

**Comment by dorkbox** [comment]
This is because the 'java system tray' has already been created or used before `SystemTray.get()` was called.

The next release will solve this problem via a native implementation of the system tray for windows.

**Comment by pun-ky** [comment]
Ok. When it will be released?

**Comment by dorkbox** [comment]
Either later today or tomorrow.

**Comment by dorkbox** [comment]
I ran out of time Friday.... I'll push the release on Monday.

**Comment by pun-ky** [comment]
Ok. Cool 😉
