### ISSUE TITLE
Show Icon when application runs in WSL environment

### ISSUE THREAD

**Issue by bardware** [dorkbox/SystemTray#88]
Hi,

I'm not a JAVA devloper myself. However, I'm using a JAVA console application that uses your library to display a TaskTray icon.  I'd love to use Ubuntu on windows (WSL) rather than `cmd` to start the software. Difference when using this application in the WSL environment is the missing TrayIcon.
Can your lib somehow detect it's running Ubuntu on Windows and use the taskbar?
Do you have an idea?

**Comment by tresf** [comment]
Is this even possible?  Last I knew, WSL [couldn't run a GUI without a dedicated X server](https://www.howtogeek.com/261575/how-to-run-graphical-linux-desktop-applications-from-windows-10s-bash-shell/).  Am I missing something?

**Comment by dorkbox** [comment]
Not missing anything -- possible to detect, but not sure if possible to show the icon ;)

**Comment by tresf** [comment]
I just tried, and WSL says that it can't find an X11 display server.

You can -- however -- run it with `java.exe`.  This is an interoperability feature.

For example, this is possible through WSL... 

Linux version:

```bash
java -jar /mnt/c/my-app.jar
```

Windows version:

```bash
java.exe -jar C:\my-app.jar
```

This has the advantage of being able to stay inside the WSL terminal window, but execute the Windows version of the app.

@dorkbox I'm not sure you can do better than this until the UI components are directly accessible, which is not really your bug to sort. :)

**Comment by dorkbox** [comment]
:D thanks for figuring this out @tresf!  I'll leave this issue open (and even include this somehow in the readme) so if anyone else has this question, there is an answer.

**Comment by tresf** [comment]
Here's a real-world use-case using a Java text-editor "jEdit"...

WSL using `java.exe` (notice the system tray icon)
```bash
 java.exe -jar C:/Program\ Files/jEdit/jedit.jar
```

<img width="714" alt="screen shot 2018-07-18 at 10 53 32 pm" src="https://user-images.githubusercontent.com/6345473/42918921-7f3321c0-8add-11e8-865a-e3c3d3f2cba0.png">

WSL using `java` (complains no X display server and aborts)
```bash
java -jar /mnt/c/Program\ Files/jEdit/jedit.jar
```

<img width="701" alt="screen shot 2018-07-18 at 10 55 07 pm" src="https://user-images.githubusercontent.com/6345473/42918961-a451bd68-8add-11e8-9f1a-4983a7000736.png">

**Comment by bardware** [comment]
Thnaks for caring. I have not tried myself by now but I understand there are X servers for Windows available. Would that work?

**Comment by dorkbox** [comment]
Installing an X server should work. See: https://www.howtogeek.com/261575/how-to-run-graphical-linux-desktop-applications-from-windows-10s-bash-shell/

**Comment by tresf** [comment]
> I understand there are X servers for Windows available. Would that work?

I've used XMing on Windows for years and it works OK, but to do as you're describing the XMing source code would have to be modified to work with the native system tray.  I still don't see this as a problem that can be solved inside a Java library. :)

**Comment by bardware** [comment]
> don't see this as a problem that can be solved inside a Java library

Any input helps! Thanks alot for caring.

I installed `XMING` and ended up with this message:
```
Unable to create tray type: '_SwingTray'
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at dorkbox.systemTray.SystemTray$1.run(SystemTray.java:965)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.RuntimeException: System Tray is not supported in this configuration! Please write an issue and include your OS type and configuration
        at dorkbox.systemTray.ui.swing._SwingTray.<init>(_SwingTray.java:60)
        ... 19 more
system tray hook failed
java.lang.NullPointerException
        at runwar.tray.Tray.addMenuItems(Tray.java:185)
        at runwar.tray.Tray.instantiateMenu(Tray.java:125)
        at runwar.tray.Tray.hookTray(Tray.java:107)
        at runwar.Server.startServer(Server.java:685)
        at runwar.Start.main(Start.java:127)
```

Please feel free to close this issue.

**Comment by dorkbox** [comment]
New release 3.15, now includes a windows native tray icon implementation (which might solve this issue)

**Comment by dorkbox** [comment]
I've now added comments to the readme regarding this issue. @tresf, thank you for your help/feedback with this.

**Comment by vaibhav112212** [comment]
https://techkorr.com/

**Comment by vaibhav112212** [comment]
https://queryplex.com/

**Comment by vaibhav112212** [comment]
https://howtat.com/

**Comment by vaibhav112212** [comment]
https://whatisss.com/

**Comment by vaibhav112212** [comment]
https://wejii.com/

**Comment by vaibhav112212** [comment]
https://prozgo.com/
