### ISSUE TITLE
dorkbox system tray cannot get it working on ubuntu 14.04

### ISSUE THREAD

**Issue by pravya191** [dorkbox/SystemTray#97]
Exception in thread "main" java.lang.UnsatisfiedLinkError: dorkbox.util.jna.linux.Gtk3.g_main_context_invoke(Ldorkbox/util/jna/linux/GMainContext;Ldorkbox/util/jna/linux/FuncCallback;Lcom/sun/jna/Pointer;)V
	at dorkbox.util.jna.linux.Gtk3.g_main_context_invoke(Native Method)
	at dorkbox.util.jna.linux.GtkEventDispatch.dispatch(GtkEventDispatch.java:328)
	at dorkbox.util.jna.linux.GtkEventDispatch.waitForEventsToComplete(GtkEventDispatch.java:131)
	at dorkbox.systemTray.SystemTray.init(SystemTray.java:846)
	at dorkbox.systemTray.SystemTray.get(SystemTray.java:1078)
	at systemtray.TestTray.<init>(TestTray.java:62)
	at systemtray.TestTray.main(TestTray.java:48)
Exception in thread "GTK Native Event Loop" java.lang.UnsatisfiedLinkError: dorkbox.util.jna.linux.Gtk3.gtk_init_check(I)Z
	at dorkbox.util.jna.linux.Gtk3.gtk_init_check(Native Method)
	at dorkbox.util.jna.linux.GtkEventDispatch$2.run(GtkEventDispatch.java:98)
/.cache/netbeans/8.2/executor-snippets/run.xml:53: Java returned: 1

**Comment by dorkbox** [comment]
Can you please open an issue here: https://git.dorkbox.com/dorkbox/SystemTray

I no longer use github.
